name = "test-printer"
leanOptions = [{name = "autoImplicit", value = false}]

[[require]]
name = "MD4Lean"
git = "https://github.com/acmepjz/md4lean"
rev = "main"

[[lean_lib]]
name = "TestPrinter"
roots = ["TestPrinter.NdjsonParser", "TestPrinter.Types", "TestPrinter.Merge", "TestPrinter.PrettyPrint", "TestPrinter.Render"]

[[lean_exe]]
name = "test-printer"
root = "Main"
