import VersoBlog

open Verso Doc Verso.Doc.Concrete Verso.Genre.Blog

namespace ArenaSite.Copy

def siteTitle : String := "Lean Kernel Arena"
def pageTitleSeparator : String := " - "

def wordmarkMark : String := "⊢"
def wordmarkText : String := "lean-kernel-arena"
def topbarGithubAria : String := "View source on GitHub"
def themeToggleAria : String := "Toggle dark mode"
def themeToggleSunGlyph : String := "☀"
def themeToggleMoonGlyph : String := "☾"

def repoUrl : String := "https://github.com/leanprover/lean-kernel-arena"
def leanUrl : String := "https://lean-lang.org/"
def zulipUrl : String := "https://leanprover.zulipchat.com/"

def footerTagline : String := "Proof checkers for Lean, tested side by side."
def footerArenaRepo : String := "Arena repo"
def footerCommunityHeading : String := "Community"
def footerLinkLean : String := "Lean"
def footerLinkZulip : String := "Zulip"

def heroKicker : String := "lean-kernel-arena"
def heroTitle : String := "Lean Kernel Arena"
def heroCopy : String :=
  "Independent proof checkers for the Lean theorem prover, run against a shared \
suite of exported proofs and scored on what they accept, what they reject, and \
how fast they get there."

def statCheckers : String := "checkers"
def statTests : String := "tests"

def acceptedGlyph : String := "✓"
def rejectedGlyph : String := "✗"
def declinedGlyph : String := "?"
def erroredGlyph : String := "!"
def eitherGlyph : String := "✓/✗"

def checkersHeading : String := "Checkers"
def testsHeading : String := "Tests"
def detailsHeading : String := "Details"
def detailedResultsHeading : String := "Detailed results"

def columnChecker : String := "Checker"
def columnVersion : String := "Version"
def columnName : String := "Name"
def columnTest : String := "Test"
def columnSize : String := "Size"
def columnExpected : String := "Expected"
def columnResult : String := "Result"

def soundnessColumn : String := "Sound"
def completenessColumn : String := "Complete"
def declinedColumn : String := "Declined"
def timeColumn : String := "Time"
def memoryColumn : String := "Memory"

def acceptedColumnTitle : String := "Correctly accepted valid proofs"
def rejectedColumnTitle : String := "Correctly rejected invalid proofs"
def declinedColumnTitle : String := "Tests declined to process or crashed"
def timeColumnTitle : String := "Virtual CPU time to process the mathlib test"
def memoryColumnTitle : String := "Peak memory usage for the mathlib test"



def completenessCard : String := "Completeness (rightfully accepted tests)"
def soundnessCard : String := "Soundness (rightfully rejected tests)"
def declinedCard : String := "Declined tests"

def declarationLink : String := "📄 Declaration"
def sourceLink : String := "🔗 Source"

def versionLabel : String := "Version"
def expectedLabel : String := "Expected"
def resultLabel : String := "Test result"
def sizeLabel : String := "Size"
def linesLabel : String := "Lines"
def exporterLabel : String := "lean4export"
def leanLabel : String := "Lean"
def exitCodeLabel : String := "exit code"
def wallTimeLabel : String := "wall time"
def instructionsLabel : String := "instructions"
def memoryLabel : String := "max rss memory"
def stdoutLabel : String := "stdout"
def stderrLabel : String := "stderr"

def noCheckers : String := "No checkers defined."
def noTests : String := "No tests available."
def noResults : String := "No test results available."
def noCheckerResults : String := "No checker results available for this test."
def missing : String := "—"

def breadcrumbRoot : String := siteTitle
def breadcrumbSeparator : String := " / "

def sourceHeading : String := "Source"
def exportHeading : String := "Exported declarations"

def checkerHeading (name : String) : String := s!"Checker \"{name}\""
def testHeading (name : String) : String := s!"Test \"{name}\""

def generatedPrefix : String := "Generated on "
def footerSeparator : String := " · "
def revisionLabel (revision : String) : String := s!"revision {revision}"
def workflowRunLabel (runId : String) : String := s!"workflow run {runId}"

def siteIntro : VersoDoc Page :=
  verso (Page) "siteIntro"
  :::
  The **Lean Kernel Arena** presents, tests and benchmarks proof checkers for the [Lean Theorem Prover](https://lean-lang.org/).
  :::

def detailsScoring : VersoDoc Page :=
  verso (Page) "detailsScoring"
  :::
  The data above is generated by running each checker on a suite of test inputs. Test inputs are either valid proofs that should be accepted (column Complete), or invalid proofs that should be rejected (column Sound). The checkers are scored based on their ability to correctly accept and reject these tests.
  :::

def measurementsPrefix : String :=
  "The time and space measurements refer to the "

def measurementsMiddle (rate : String) : String :=
  s!" test case, the largest correct test in the suite. The Time column shows virtual CPU time, calculated from instruction counts using a fixed rate of {rate}instr/s. This provides consistent performance comparison across different hardware, though it does not reflect parallel processing capabilities that some checkers may use."

def detailsDeclining : VersoDoc Page :=
  verso (Page) "detailsDeclining"
  :::
  Checkers that do not implement all features may choose to explicitly decline to process certain tests (column Declined). These tests are not taken into account for correctness scoring. Tests that crash the checker are also considered declined.
  :::

def detailsInterface : VersoDoc Page :=
  verso (Page) "detailsInterface"
  :::
  For more details on the interface for external checks, and how to submit these, see the project's [`README.md` file](https://github.com/leanprover/lean-kernel-arena).
  :::

def tarballPrefix : String :=
  "A tarball of the test suite (excluding tests larger than 10 MB) is available for download: "

def tarballSuffix (goodCount badCount : Nat) (size : String) : String :=
  s!" ({goodCount} good tests, {badCount} bad tests, {size}). The tarball contains subdirectories "

def tarballBetweenDirs : String := " and "

def tarballTail : String :=
  " based on expected results, making it easy to test your own checker implementation."

def detailsTutorial : VersoDoc Page :=
  verso (Page) "detailsTutorial"
  :::
  The test suite includes a set of [tutorial test cases](test/tutorial/) that exercise individual features of the Lean type system step by step, from basic definitions through inductives, recursors, projections, definitional equality rules, and quotient types. Each tutorial test is a small self-contained environment, making them a useful starting point for developing and debugging a new kernel checker.
  :::

def detailsExtending : VersoDoc Page :=
  verso (Page) "detailsExtending"
  :::
  We are interested in extending our test suite, in particular tests that should be rejected are a useful help for authors of new kernel checkers.
  :::

end ArenaSite.Copy
