url = "https://github.com/FawadHa1der/evm_proof_checker"
ref = "main"
rev = "055a6b9cad082f13838a50ba92a937d347690d13"
build = "npm install --no-audit --no-fund && node tools/build.js"
run = "node bin/evmlean.js $IN"
