name: Arena run

on:
  workflow_call:
    inputs:
      record:
        type: boolean
        default: false
      publish:
        type: boolean
        default: false
      checker:
        type: string
        default: ""
      pin:
        description: Toolchain or commit
        type: string
        default: ""
      rerun:
        type: boolean
        default: false

jobs:
  arena:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        if: inputs.publish
        uses: actions/configure-pages@v4

      - name: Checkout results
        uses: actions/checkout@v4
        with:
          ref: results
          path: _results

      - name: Set perf_event_paranoid
        run: sudo sysctl -w kernel.perf_event_paranoid=1

      - name: Cache exports
        uses: actions/cache@v4
        with:
          path: _build/tests
          key: exports-${{ runner.os }}-${{ github.sha }}
          restore-keys: exports-${{ runner.os }}-

      - name: Build tests
        run: lake exe lka build-test ${{ github.event_name == 'pull_request' && '--skip-ci' || '' }}
        shell: "nix develop -c bash -euxo pipefail {0}"

      - name: Run checkers
        env:
          CHECKER: ${{ inputs.checker }}
          PIN: ${{ inputs.pin }}
          RERUN: ${{ inputs.rerun }}
          ARENA_RUNNER: github-${{ runner.os }}
        run: |
          lake exe lka run \
            ${CHECKER:+--checker "$CHECKER"} \
            ${PIN:+--pin "$PIN"} \
            $([ "$RERUN" = true ] && echo --rerun)
        shell: "nix develop -c bash -euxo pipefail {0}"

      - name: Push results
        if: inputs.record
        working-directory: _results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then exit 0; fi
          git commit -m "${GITHUB_RUN_ID}" -m "Dispatched-by: ${GITHUB_ACTOR}"
          git push origin HEAD:results

      - name: Build site
        run: lake exe lka build-site
        shell: "nix develop -c bash -euxo pipefail {0}"

      - name: Upload artifact
        if: inputs.publish
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_out"

      - name: Deploy to GitHub Pages
        if: inputs.publish
        id: deployment
        uses: actions/deploy-pages@v4
