name: still-nanoda

on:
  workflow_call:
    inputs:
      tests: {type: string, default: ''}
      record: {type: boolean, default: false}
  workflow_dispatch:
    inputs:
      tests: {type: string}

jobs:
  still-nanoda:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: SchrodingerZhu/still-nanoda
          ref: 06a07b74436f8a111df836312ccac3a41b93c7b6
          path: checker

      - uses: dtolnay/rust-toolchain@stable

      - run: sudo apt-get update -qq && sudo apt-get install -y -qq libgmp-dev

      - name: Build
        working-directory: checker
        run: |
          cargo build --release
          cat > config.json <<__END__
           {
             "use_stdin": true,
             "nat_extension": true,
             "string_extension": true,
             "unpermitted_axiom_hard_error": false,
             "unsafe_permit_all_axioms": true,
             "num_threads": 4
           }
          __END__

      - uses: ./.github/actions/measure
        with:
          checker: still-nanoda
          revision: 06a07b7
          work: checker
          run: |
            target/release/nanoda_bin config.json < "$IN" || exit 1
          source-url: https://github.com/SchrodingerZhu/still-nanoda
          tests: ${{ inputs.tests }}
          record: ${{ inputs.record || false }}
