name: nanoda

on:
  workflow_call:
    inputs:
      tests: {type: string, default: ''}
      record: {type: boolean, default: false}
  workflow_dispatch:
    inputs:
      tests: {type: string}

jobs:
  nanoda:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: ammkrn/nanoda_lib
          ref: ddfac2bf5a7b56cb46e141494427ff3dd55963c7
          path: checker

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        working-directory: checker
        run: |
          cargo build --release
          cat > config.json <<__END__
           {
             "use_stdin": true,
             "nat_extension": true,
             "string_extension": true,
             "unpermitted_axiom_hard_error": false,
             "unsafe_permit_all_axioms": true,
             "num_threads": 4
           }
          __END__

      - uses: ./.github/actions/measure
        with:
          checker: nanoda
          revision: ddfac2b
          work: checker
          run: |
            target/release/nanoda_bin config.json < "$IN"
            case $? in 
              0) exit 0 ;;
              2) exit 2 ;;
              *) exit 1 ;;
            esac
          source-url: https://github.com/ammkrn/nanoda_lib
          tests: ${{ inputs.tests }}
          record: ${{ inputs.record || false }}
