name: rpylean

on:
  workflow_call:
    inputs:
      tests: {type: string, default: ''}
      record: {type: boolean, default: false}
  workflow_dispatch:
    inputs:
      tests: {type: string}

jobs:
  rpylean:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: Julian/rpylean
          ref: 1f6d2205d3958484b7de351d314a5e02896b9fab
          path: checker

      - uses: actions/setup-python@v5
        with:
          python-version: pypy-2.7

      - uses: actions/checkout@v4
        with:
          repository: pypy/pypy
          path: checker/pypy

      - uses: extractions/setup-just@v4

      - run: sudo apt-get update -qq && sudo apt-get install -y -qq libffi-dev pkg-config

      - name: Build
        working-directory: checker
        run: |
          printf 'PYPY_CHECKOUT=./pypy\n' > .env
          just translate

      - uses: ./.github/actions/measure
        with:
          checker: rpylean
          revision: 1f6d220
          work: checker
          run: |
            ./rpylean-c check "$IN" || exit 1
          source-url: https://github.com/Julian/rpylean
          declines: Mathlib
          tests: ${{ inputs.tests }}
          record: ${{ inputs.record || false }}
